cms_project/Models/ViewModel/SideBarViewModel.cs
using cms_project.Models.Entites;

namespace cms_project.Models.ViewModel
{
    public class SideBarViewModel
    {
        public List<AttachmentComplaint> AttachmentComplaints { get; set; }
        public List<Complaint> Complaints { get; set; }
        public string Role { get; set; }
        public List<string> Permission { get; set; }    = new List<string>();
         
    }
}

cms_project/Components/Main/SidebarViewComponent.cs
using cms_project.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

public class SidebarViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        var roleClaim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "Role");
        var user = HttpContext.User;
        var permissions = user.FindAll("Permission").Select(c => c.Value).ToList();
        var role = user.FindFirst("Role")?.Value;
        var claims = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "Claims");
        return View(new SideBarViewModel { Role = role ,Permission=permissions});
    }
}

cms_project/Components/Main/TopbarViewComponent.cs
using cms_project.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Linq;
using cms_project.Models.Entites;
using cms_project.Data;

namespace cms_project.Componant.Main
{
    public class TopbarViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext context;

        public TopbarViewComponent(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IViewComponentResult Invoke()
        {
            var username = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "Name")?.Value ?? "Guest";
            var userIdClaim = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value;

            int.TryParse(userIdClaim, out int userId);
            
             var  notifications = context.Set<Notification>()
                    .Where(n => n.UserId == userId)
                    .OrderByDescending(n => n.CreatedDate)
                    .Take(5)
                    .ToList();
           

            var model = new TopBarViewModel
            {
                Username = username,
                Notifications = notifications
            };

            return View(model);
        }
    }
}

cms_project/Controllers/ComplaintsController.cs
using System.Security.Claims;
using System.Xml.Linq;
using cms_project.Data;
using cms_project.Models.Entites;
using cms_project.Models.ViewModel;
using cms_project.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace cms_project.Controllers
{
     
    public class ComplaintsController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly IWebHostEnvironment environment;
        private readonly EmailService _emailService;
        public ComplaintsController(ApplicationDbContext dbContext , IWebHostEnvironment environment,EmailService emailService) 
        { 
        this.context = dbContext;
        this.environment = environment;
            this._emailService= emailService;   
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {

            var complaintTypes= context.ComplaintTypes.Select(x=>new ComplaintTypesViewModel
            {
               Id  = x.Id,
               Name =x.Name,
            }).ToList();
            return View(new ComplaintViewModel() { ComplaintTypeList=complaintTypes});
        }
    


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(ComplaintViewModel cvm)
        {
            if (!ModelState.IsValid)
            {
                var complaintTypes = context.ComplaintTypes.Select(x => new ComplaintTypesViewModel
                {
                    Id = x.Id,
                    Name = x.Name,
                }).ToList();
                cvm.ComplaintTypeList = complaintTypes;
                return View(cvm);
            }

            var userIdClaim = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!int.TryParse(userIdClaim, out int userId))
            {
                return BadRequest("Cannot Send The Request");
            }

            var userEmail = User.FindFirstValue(ClaimTypes.Email);

            Complaint complaint = new Complaint()
            {
                ComplaintTypeId = cvm.ComplaintTypeId,
                Title = cvm.Title,
                Description = cvm.Description,
                CreatedBy = userId,
                StatusId = 1,
                AttachmentComplaints = new List<AttachmentComplaint>()  // ensure it's not null
            };

            if (cvm.Attachments != null && cvm.Attachments.Count > 0)
            {
                var uploadFolder = Path.Combine("wwwroot", "attachment");
                if (!Directory.Exists(uploadFolder))
                {
                    Directory.CreateDirectory(uploadFolder);
                }

                foreach (var file in cvm.Attachments)
                {
                    if (file.Length > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var fullPath = Path.Combine(uploadFolder, fileName);

                        using (var stream = new FileStream(fullPath, FileMode.Create))
                        {
                            await file.CopyToAsync(stream);
                        }

                        complaint.AttachmentComplaints.Add(new AttachmentComplaint
                        {
                            AttachmentName = fileName
                        });
                    }
                }
            }

            // Only add & save once
            context.Set<Complaint>().Add(complaint);
            await context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Your complaint has been successfully submitted.";

            _emailService.Send(userEmail, "Complaint Submitted",
                $"Dear {User.FindFirstValue("Name")}, Thank you for submitting the complaint.");

            var notification = new Notification
            {
                Id = Guid.NewGuid().ToString(),
                Title = "Complaint Submitted Successfully",
                UserId = userId,
                CreatedDate = DateTime.Now
            };
            context.Set<Notification>().Add(notification);
            await context.SaveChangesAsync();

            return RedirectToAction("Create");
        }


        [HttpGet]
        [Authorize(Policy = "Manage Complaints")]

        public IActionResult ShowComplaint()
        {

            var userComplaint = context.Set<Complaint>().Include(x => x.UserAccount).Include(x => x.AttachmentComplaints)
                                                     .Include(x => x.ComplaintType).OrderByDescending(x=>x.CreatedDate)
                  .Select(x => new ComplaintListViewModel
                  {
                      Id = x.Id,
                      ComplaintType = x.ComplaintType.Name,
                      ComplaintTypeId = x.ComplaintType.Id,
                      CreatedDate = x.CreatedDate,
                      Description = x.Description,
                      Title = x.Title,
                      Username = x.UserAccount.Name,
                      Status = x.Status.StatusName,
                      Attachment = x.AttachmentComplaints.Select(a => a.AttachmentName).ToList(),
                      ComplaintHistories = x.ComplaintHistories,
                      AssignToId = x.AssignedTo ?? 0,
                      StatusId = x.StatusId,
                      CreatedBy = x.CreatedBy
                  })
                .ToList();
            return View(userComplaint);
        }
        [HttpGet]
        [Authorize]
        public IActionResult ShowHistoryComplaint()
        {
            var userIdClaim = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!int.TryParse(userIdClaim, out int userId))
            {
                return BadRequest("Cannot Get User Information");
            }

            var userComplaint = context.Set<Complaint>()
                .Where(x => x.CreatedBy == userId)
                .Include(x => x.UserAccount)
                .Include(x => x.AttachmentComplaints)
                .Include(x => x.ComplaintType)
                .Select(x => new ComplaintListViewModel
                {
                    Id=x.Id,
                    Username = x.UserAccount.Name,
                    ComplaintType = x.ComplaintType.Name,
                    CreatedDate = x.CreatedDate,
                    Description = x.Description,
                    Title = x.Title,
                    Status = x.Status.StatusName,
                    Attachment = x.AttachmentComplaints
                                 .Select(x => x.AttachmentName).ToList()

                })
                .ToList();

            return View(userComplaint);
        }
        [Authorize]
        public async Task<IActionResult> ComplaintDetails(Guid id)
            {


            var complaint = await context.Set<Complaint>()
              .Where(c => c.Id.Equals(id))
              .Select(x => new ComplaintListViewModel
              {
                  Id = x.Id,
                  ComplaintType = x.ComplaintType.Name,
                  ComplaintTypeId = x.ComplaintType.Id,
                  CreatedDate = x.CreatedDate,
                  Description = x.Description,
                  Title = x.Title,
                  Username = x.UserAccount.Name,
                  Status = x.Status.StatusName,
                  Attachment = x.AttachmentComplaints.Select(a => a.AttachmentName).ToList()   ,
                  ComplaintHistories = x.ComplaintHistories ,
                  AssignToId =x.AssignedTo ?? 0,
                  AssigneeName = x.AssignedUser.Name ?? "Not Assigned",
                  StatusId = x.StatusId,
                  CreatedBy =x.CreatedBy
              })
               .FirstOrDefaultAsync();

            

            var users = await context.Set<UserAccount>().Where(x=>x.ComplaintTypeResolverId ==complaint.ComplaintTypeId).ToListAsync();
            ViewBag.Users = new SelectList(users, "Id", "Name");
            ViewBag.userId = User.FindFirstValue(ClaimTypes.NameIdentifier);


            return View(complaint);
        }

        [Authorize(Policy = "Resolve Complaint")]

        public async Task<IActionResult> InboxComplaint()
        {
            var userIdClaim = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!int.TryParse(userIdClaim, out int userId))
            {
                return BadRequest("Cannot Get User Information");
            }

            var userComplaint = context.Set<Complaint>()
                .Where(x => x.AssignedTo == userId)
                .Include(x => x.UserAccount)
                .Include(x => x.AttachmentComplaints)
                .Include(x => x.ComplaintType)
                  .Select(x => new ComplaintListViewModel
                  {
                      Id = x.Id,
                      ComplaintType = x.ComplaintType.Name,
                      ComplaintTypeId = x.ComplaintType.Id,
                      CreatedDate = x.CreatedDate,
                      Description = x.Description,
                      Title = x.Title,
                      Username = x.UserAccount.Name,
                      Status = x.Status.StatusName,
                      Attachment = x.AttachmentComplaints.Select(a => a.AttachmentName).ToList(),
                      ComplaintHistories = x.ComplaintHistories,
                      AssignToId = x.AssignedTo ?? 0,
                      StatusId = x.StatusId,
                      CreatedBy = x.CreatedBy
                  })
                .ToList();

            return View(userComplaint);
        }

        [Authorize(Policy = "Resolve Complaint")]

        public async Task<IActionResult> HistoryResolverComplaint()
        {
            var userIdClaim = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!int.TryParse(userIdClaim, out int userId))
            {

cms_project/Controllers/DashboardController.cs
using System.Security.Claims;
using cms_project.Data;
using cms_project.Models.Entites;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace cms_project.Controllers
{
    

    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext context;
        

        public DashboardController(ApplicationDbContext context)
        {
            this.context = context;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            int userId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);

            var user = await context.Set<UserAccount>()
                                    .Include(u => u.Role)
                                    .FirstOrDefaultAsync(u => u.Id == userId);

            string roleName = user?.Role?.Name;
            ViewBag.Role = roleName;

            if (roleName == "SuperAdmin")
            {
                ViewBag.PendingCount = await context.Set<Complaint>().CountAsync(c => c.StatusId == (int)ComplaintStatus.Pending);
                ViewBag.InProgressCount = await context.Set<Complaint>().CountAsync(c => c.StatusId == (int)ComplaintStatus.InProgress);
                ViewBag.ResolvedCount = await context.Set<Complaint>().CountAsync(c => c.StatusId == (int)ComplaintStatus.Resolved);
                ViewBag.CompletedCount = await context.Set<Complaint>().CountAsync(c => c.StatusId == (int)ComplaintStatus.Closed);
            }
            else
            {
                ViewBag.PendingCount = await context.Set<Complaint>().CountAsync(c => c.StatusId == (int)ComplaintStatus.Pending && c.CreatedBy == userId);
                ViewBag.InProgressCount = await context.Set<Complaint>().CountAsync(c => c.StatusId == (int)ComplaintStatus.InProgress && c.CreatedBy == userId);
                ViewBag.ResolvedCount = await context.Set<Complaint>().CountAsync(c => c.StatusId == (int)ComplaintStatus.Resolved && c.CreatedBy == userId);
                ViewBag.CompletedCount = await context.Set<Complaint>().CountAsync(c => c.StatusId == (int)ComplaintStatus.Closed && c.CreatedBy == userId);
            }


      

            var announcements = await context.Announcements
                .Where(a => a.IsActive)
                .OrderByDescending(a => a.DatePosted)
                .ToListAsync();

            var threeDaysAgo = DateTime.Now.AddDays(-3);

            ViewBag.OverdueCount = await context.Set<Complaint>()
                .Where(c => c.StatusId != (int)ComplaintStatus.Resolved && c.StatusId != (int)ComplaintStatus.Closed)
                .Where(c => c.CreatedDate < threeDaysAgo)
                .CountAsync();

            var complaintStats = await context.Set<Complaint>()
                .GroupBy(c => c.Status)
                .Select(g => new { Status = g.Key, Count = g.Count() })
                .ToListAsync();

            ViewBag.ChartLabels = complaintStats.Select(s => s.Status).ToArray();
            ViewBag.ChartData = complaintStats.Select(s => s.Count).ToArray();

            return View(announcements);
        }

        public ActionResult FAQ()
        {
            return View();
        }


        [HttpGet]
        [Authorize(Policy = "Announcement")]
        public ActionResult CreateAnnouncement()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Policy = "Announcement")]
        public ActionResult CreateAnnouncement(Announcement model)
        {
            if (ModelState.IsValid)
            {
                model.DatePosted = DateTime.Now;
                model.IsActive = true;

                context.Announcements.Add(model);
                context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(model);
        }

       
        
        [HttpGet]
        public IActionResult DeleteAnnouncement(int id)
        {
            var announcement = context.Announcements.Find(id);
            if (announcement != null)
            {
                context.Announcements.Remove(announcement);
                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }









    }
}

cms_project/Views/Shared/Components/Sidebar/Default.cshtml
@model cms_project.Models.ViewModel.SideBarViewModel

<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-university"></i>
        </div>
        <div class="sidebar-brand-text mx-3"><sup>WCH</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    @if (Model.Permission.Contains("View Dashboard"))
    {

        <li class="nav-item active">
            <a class="nav-link" asp-action="Index" asp-controller="Dashboard">
                <i class="fas fa-fw fa-home"></i>   
                <span>Dashboard</span>
            </a>
        </li>
    }

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Nav Items for Students -->
    @if (Model.Role == "Student")
    {
        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="Complaints" asp-action="Create"
            aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-fw fa-plus-circle"></i> <!-- أيقونة زائد للدلالة على إضافة -->
                <span>Add Complaint</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="Complaints" asp-action="ShowHistoryComplaint"
            aria-expanded="true" aria-controls="collapseUtilities">
                <i class="fas fa-fw fa-history"></i> <!-- أيقونة تاريخ -->
                <span>Complaint History</span>
            </a>
            <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Custom Utilities:</h6>
                    <a class="collapse-item" href="utilities-color.html">Colors</a>
                    <a class="collapse-item" href="utilities-border.html">Borders</a>
                    <a class="collapse-item" href="utilities-animation.html">Animations</a>
                    <a class="collapse-item" href="utilities-other.html">Other</a>
                </div>
            </div>
        </li>
    }

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Nav Items based on Permissions -->
    @if (Model.Permission.Contains("Resolve Complaint"))
    {
        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="Complaints" asp-action="InboxComplaint"
            aria-expanded="true" aria-controls="collapsePages">
                <i class="fas fa-fw fa-inbox"></i> 
                <span>Complaint Inbox</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="Complaints" asp-action="HistoryResolverComplaint"
            aria-expanded="true" aria-controls="collapsePages">
                <i class="fas fa-fw fa-inbox"></i> 
                <span>History Resolver</span>
            </a>
        </li>
    }
    @if (Model.Permission.Contains("Manage Complaints"))
    {
        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="Complaints" asp-action="ShowComplaint"
            aria-expanded="true" aria-controls="collapsePages">
                <i class="fas fa-fw fa-list-alt"></i> <!-- أيقونة قائمة -->
                <span>Complaint List</span>
            </a>
        </li>
    }

    <!-- Admin Role Items -->
    @if (Model.Permission.Contains("Manage Roles"))
    {
        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="MangementAdmin" asp-action="ManageRoles"
            aria-expanded="true" aria-controls="collapsePages">
                <i class="fas fa-fw fa-user-shield"></i> 
                <span>Management Role</span>
            </a>
        </li>

    }
    @if (Model.Permission.Contains("Manage User"))
    {
        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="MangementAdmin" asp-action="MangementTableUser"
            aria-expanded="true" aria-controls="collapsePages">
                <i class="fas fa-fw fa-users-cog"></i>
                <span>Management User</span>
            </a>
        </li>

    }
    @if (Model.Permission.Contains("Manage Complaint Types"))
    {
        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="MangementAdmin" asp-action="MangementTableComplaintType"
            aria-expanded="true" aria-controls="collapsePages">
                <i class="fas fa-fw fa-tags"></i>
                <span>Complaint Type</span>
            </a>
        </li>

    }
    @if (Model.Permission.Contains("Announcement"))
    {
        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="Dashboard" asp-action="CreateAnnouncement"
            aria-expanded="true" aria-controls="collapsePages">
                <i class="fas fa-fw fa-bell"></i>
                <span>Announcements</span>
            </a>
        </li>
    }
    @if (Model.Permission.Contains("Email Setting"))
    {

        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="MangementAdmin" asp-action="EditEmailSetting" asp-route-id="1"
            aria-expanded="true" aria-controls="collapsePages">
                <i class="fas fa-fw fa-envelope"></i>
                <span>Email Settings</span>
            </a>
        </li>

    }

  

</ul>
<!-- End of Sidebar -->